# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$KD_REGISTRY_USER" -p "$KD_REGISTRY_PASSWORD" $KD_REGISTRY_REGISTRY
  - docker login -u "$HUB_REGISTRY_USER" -p "$HUB_REGISTRY_PASSWORD"

build-master:
  stage: build
  script:
    - docker build --pull -t "$KD_REGISTRY_REGISTRY/$CI_PROJECT_NAME" -t "keptdream/subsonic" .
    - docker push "$KD_REGISTRY_REGISTRY/$CI_PROJECT_NAME"
    - docker push "keptdream/subsonic"
  only:
    - master
