version: '3.1'

services:
  app:
    build: .
    restart: always
    ports:
      - 4040:4040
    volumes:
      - music:/data/music
      - playlists:/data/playlists
      - podcasts:/data/podcasts
      - data:/data/subsonic
volumes:
  music:
  playlists:
  podcasts:
  data:
